version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - "8000:3000"
    environment:
      TOKEN_KEY: "${TOKEN_KEY}"
  users:
    build: ./users-api
    ports:
      - "8080:3000"
    environment:
      MONGODB_CONNECTION_URI: "mongodb://root:example@db:27017/user?authSource=admin"
      AUTH_API_ADDRESS: "auth:3000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "user"
  nextapp:
    build:
      context: ./frontend-app
      args:
        env: local
    ports:
      - "4200:80"
    environment:
      USERS_API: "${USERS_API}"
