apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: mohitsoni02/auth-api:latest
          volumeMounts:
            - name: auth-volume
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: auth-volume
          secret:
            secretName: auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  TOKEN_KEY: c2VjdXJla2V5