apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # select the users pod and expose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # label by which pod can be selected
    spec:
      containers:
        - name: frontend-app-container
          image: mohitsoni02/k8-frontend-app:latest
          env:
            - name: USERS_API
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: users_api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  users_api: http://users-service:8000
