apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # select the users pod and expose
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users # label by which pod can be selected
    spec:
      containers:
        - name: users-api
          image: mohitsoni02/k8-users:latest
          volumeMounts:
            - name: users-volume
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: users-volume
          secret:
            secretName: users-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  .env: TU9OR09EQl9DT05ORUNUSU9OX1VSST1tb25nb2RiK3NydjovL21hc3RlckRldjpteUJhY2tlbmREQkBkZXBsb3ljbHVzdGVyLnh3bjF0OXgubW9uZ29kYi5uZXQvdXNlcj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1kZXBsb3lDbHVzdGVyCkFVVEhfQVBJX0FERFJFU1M9YXV0aC1zZXJ2aWNlLmRlZmF1bHQ6MzAwMA==
